### ISSUE TITLE
Example application for Go library

### ISSUE THREAD

**Issue by leina05** [osohq/oso#747]
It would be great to have an example application for Oso's new [Go library](https://pkg.go.dev/github.com/osohq/go-oso). Something similar to https://github.com/osohq/oso-flask-tutorial, which we use for our "Add to your application" guide  in Python. We'd like to write a similar guide based on this example Go application.

**Comment by delicb** [comment]
@leina05 is [this](https://github.com/delicb/oso-go-tutorial/) something along the lines of what you had in mind?

I have implemented most of it locally and then saw this ticket. It was a relatively short effort to modify my examples to align with what is implemented in the flask tutorial. I did simplify a model a bit since I did not see a use for some columns and some tables, but it should be fairly easy to extend it if the accompanying tutorial needs it. 

End-to-end tests are missing, but there are some unit tests implemented. 

Please let me know if you think you can use this repo or you think something should be improved.

**Comment by saolsen** [comment]
Wow this is awesome! Thanks so much for sharing this with us!

We'll take a look at it and see what it would take to base our “Add Oso to a Go Application” tutorial on it.

**Comment by delicb** [comment]
@saolsen 
Sure thing. Please let me know how you feel about the repo and if you would like something to change. 
I just figured that I did not finish organization-related endpoints. I will probably do that as well tomorrow.

You can reach me on OSO slack as well if needed.

**Comment by dhatch** [comment]
Hey @delicb ! Just wanted to let you know we still have this on our list :) 

We're in the process of doing some revamps to our Python "add to your app" guide. After that we're going to take a look at this and see what we'd need to base the go version of that guide on this.

Again, thanks for sharing this with us! We're really excited to get more Go guides on our site.

**Comment by delicb** [comment]
@dhatch Thanks for letting me know. There is definitely no rush from my side :).

**Comment by dhatch** [comment]
Hi @delicb! We recently revamped our Getting Started section to include features in the new 0.20.0 release. There are now [Quickstart](https://docs.osohq.com/go/getting-started/quickstart.html) and [Add to Your Application](https://docs.osohq.com/go/getting-started/application.html) guides for Go!

We changed the content of the guides to use role-based access control policies, so the example apps for all languages, including Go, are completely new.

I'm going to close this issue since we now have an example for Go, but please let us know if you have feedback on the new guides and examples. You can reach me directly in [Slack](http://join-slack.osohq.com) (`@dhatch`) or anyone else on the team will see feedback in the #community or other channels.
